services:
  echo-golinter:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        COMPOSE_USER_ID: ${COMPOSE_USER_ID}
        COMPOSE_GROUP_ID: ${COMPOSE_GROUP_ID}
    volumes:
      - ../../:/app
    working_dir: /app